services:
  WEB1:
    build: .
    image: test-app:1.0
    environment:
      - Port=3001
      - AppName=TestAppOne
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=Pirrorfuthertogether2025.
      - MYSQL_USER=sizwe
      - MYSQL_HOST=db
    expose:
      - 3001

  nginx:
    build: ./nginx
    depends_on:
      - WEB1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
